### ISSUE TITLE
Terms on the start screen menu

### ISSUE THREAD

**Issue by Thaza-Kun** [Thaza-Kun/obsidian-translations#1]
Issues on terms:
start-screen > 
    "option-open-help-vault-description": "Buka Peti Nota \"Demo & Help\"." (Need clarification on the term "Demo & Help" from the documentation)
    "button-browse": "Browse" (Need clarification on the term "Browse")

**Comment by MagusWyvern** [comment]
Browse could be changed to "Cari folder" since it prompts the user to look for a vault?

**Comment by Thaza-Kun** [comment]
Yeah, I think that is a reasonable enough solution
